game: &Autopelago "Autopelago"

name: "niyrme-rat{number}"

*Autopelago :
  # game
  progression_balancing: "random-range-30-40"
  accessibility: "full"
  fill_with_determination: false
  &AutopelagoVictoryLocation victory_location:
    &AutopelagoEndLong snakes_on_a_planet: 1
    secret_cache: 9
    captured_goldfish: 0
  enabled_buffs:
    - "Well Fed" # Gets more done
    - "Lucky" # One free success
    - "Energized" # Moves faster
    - "Stylish" # Better RNG
    - "Confident" # Ignore a trap
    - "Smart" # Next check is progression
  &AutopelagoTraps enabled_traps:
    - "Upset Tummy" # Gets less done
    - "Unlucky" # Worse RNG
    - "Sluggish" # Moves slower
    - "Distracted" # Skip a "step"
    - "Startled" # Run towards start
    - "Conspiratorial" # Next check is trap
  msg_changed_target:
    - "Oh, hey, what's that thing over there at {LOCATION}? Is it progression?"
    - "Something at {LOCATION} smells good!"
  msg_enter_go_mode:
    - "Go mode. Gotta go fast!"
    - "I am speed!"
  msg_enter_bk:
    - "BURGER KING!"
  msg_remind_bk:
    - "Generic BK message"
    - "Please get me out of Burger King. I am getting fat!"
  msg_exit_bk:
    - "Burger king was tasty"
    - "Time to work off all those calories..."
  msg_completed_goal:
    - "NUMBER ONE VICTORY ROYALE!"

  triggers:
    # disable traps for long ending
    - option_category: *Autopelago
      option_name: *AutopelagoVictoryLocation
      option_result: *AutopelagoEndLong
      options:
        *Autopelago :
          *AutopelagoTraps : []
