game: &Jigsaw "Jigsaw"

name: "niyrme-puuule{number}"

*Jigsaw :
  # game
  progression_balancing: "random-range-low-0-10"
  accessibility: "full"

  # gameplay
  number_of_pieces: "random-range-middle-100-200"
  rotations: "no_rotation"

  # image
  orientation_of_image:
    square: 0
    landscape: 1
    portrait: 0
  which_image:
    1: 1
    22: 1
    31: 1
    34: 1

  # extra pieces
  percentage_of_extra_pieces: "random-range-high-5-10"
  number_of_piece_bundles: "random-range-low-25-50"
  minimum_number_of_pieces_per_bundle: 2
  add_fillers: false
  percentage_fillers_itempool: 0
  checks_out_of_logic: 0

  # piece order
  piece_order_type: "random_order"
  strictness_piece_order_type: "random-range-middle-75-100"
  piece_order: "random_order"
  strictness_piece_order: "random-range-middle-75-100"

  # traps
  starting_fake_pieces: 0
  number_of_fake_piece_bundles: 0
  number_of_rotate_traps: 0
  number_of_swap_traps: 0
  death_link: 0

  # others
  enable_clues: false
  total_size_of_image: 85
