name: "NiyrmeSide{number}"
description: "Side games"
game:
  &Rat "Autopelago": 1
  &Mines "ChecksFinder": 0
  &Jigsaw "Jigsaw": 1
  &Yacht "Yacht Dice": 1

requires:
  version: "0.6.1"

triggers:
  - option_name: "game"
    option_result: *Rat
    options: { "": { "name": "NiyrmeRat{number}" } }
  - option_name: "game"
    option_result: *Mines
    options: { "": { "name": "NiyrmeMines{number}" } }
  - option_name: "game"
    option_result: *Jigsaw
    options: { "": { "name": "NiyrmePuuule{number}" } }
  - option_name: "game"
    option_result: *Yacht
    options: { "": { "name": "NiyrmeYacht{number}" } }

*Rat :
  # game
  progression_balancing: "random-range-30-40"
  accessibility: "full"
  fill_with_determination: false
  victory_location:
    snakes_on_a_planet: 0
    secret_cache: 1
    captured_goldfish: 0
  enabled_buffs:
    - "Well Fed" # Gets more done
    - "Lucky" # One free success
    - "Energized" # Moves faster
    - "Stylish" # Better RNG
    - "Confident" # Ignore a trap
    - "Smart" # Next check is progression
  enabled_traps:
    - "Upset Tummy" # Gets less done
    - "Unlucky" # Worse RNG
    - "Sluggish" # Moves slower
    - "Distracted" # Skip a "step"
    - "Startled" # Run towards start
    - "Conspiratorial" # Next check is trap
  msg_changed_target:
    - "Oh, hey, what's that thing over there at {LOCATION}? Is it progression?"
    - "Something at {LOCATION} smells good!"
  msg_enter_go_mode:
    - "Go mode. Gotta go fast!"
  msg_enter_bk:
    - "BURGER KING!"
  msg_remind_bk:
    - "Generic BK message"
    - "Please get me out of Burger King. I am getting fat!"
  msg_exit_bk:
    - "Burger king was tasty"
  msg_completed_goal:
    - "NUMBER ONE VICTORY ROYALE!"

*Mines :
  # game
  progression_balancing: "random-range-high-45-55"
  accessibility: "full"

*Jigsaw :
  # game
  progression_balancing: "random-range-low-0-10"
  accessibility: "full"
  enable_forced_local_filler_items: true

  # gameplay
  number_of_pieces: "random-range-middle-150-300"
  rotations: "no_rotation"

  # image
  orientation_of_image:
    square: 0
    landscape: 1
    portrait: 0
  which_image:
    1: 1
    22: 1
    31: 1
    34: 1

  # extra pieces
  percentage_of_extra_pieces: "random-range-high-5-10"
  maximum_number_of_real_items: 250
  minimum_number_of_pieces_per_real_item: 1
  placement_of_fillers: "local_only"
  permillage_of_checks_out_of_logic: 5

  # piece order
  piece_order_type: "random_order"
  strictness_piece_order_type: "random-range-high-80-100"
  piece_order: "random_order"
  strictness_piece_order: 80

  # traps
  fake_pieces: 0
  rotate_traps: 0
  swap_traps: 0

  # others
  enable_clues: false
  total_size_of_image: 85

*Yacht :
  # game
  progression_balancing: "random-range-middle-30-50"
  accessibility: "full"
  game_difficulty: "medium"
  score_for_last_check: "random-range-low-1000-1100"
  &YachtGoalScore score_for_goal: "random-range-low-777-999"
  &YachtMinDiceAndRolls minimal_number_of_dice_and_rolls:
    "5_dice_and_3_rolls": 48
    "5_dice_and_5_rolls": 0
    &YachtMinDiceAndRolls6d4r "6_dice_and_4_rolls": 1
    &YachtMinDiceAndRolls7d3r "7_dice_and_3_rolls": 1
    "8_dice_and_2_rolls": 0
  number_of_dice_fragments_per_dice: "random-high"
  number_of_roll_fragments_per_roll: "random-high"
  number_of_starting_categories: "random-range-low-2-3"

  # extra progression
  weight_of_dice: 5
  weight_of_roll: 20
  weight_of_fixed_score_multiplier: 30
  weight_of_step_score_multiplier: 0
  weight_of_double_category: 50
  weight_of_points: 20
  points_size: "mix"

  # extra items
  minimize_extra_items: "no_dont"
  add_bonus_points: "sure"
  add_story_chapters: "never"
  which_story: "random_story"

  # misc
  allow_manual_input: "no_dont_allow"
  receive_death_link: "yes"

  triggers:
    - option_category: *Yacht
      option_name: *YachtMinDiceAndRolls
      option_result: *YachtMinDiceAndRolls6d4r
      options:
        *Yacht :
          *YachtGoalScore : "random-range-high-777-999"
    - option_category: *Yacht
      option_name: *YachtMinDiceAndRolls
      option_result: *YachtMinDiceAndRolls7d3r
      options:
        *Yacht :
          *YachtGoalScore : "random-range-middle-777-999"
