name: "NiyrmeMain{number}"
description: "Main games"
game:
  &AHiT "A Hat in Time": 1
  &HK "Hollow Knight": 0
  &OuterWilds "Outer Wilds": 0
  &SlayTheSpire "Slay the Spire": 0
  &Terraria "Terraria": 0

requires:
  version: "0.6.1"

triggers:
  - option_name: "game"
    option_result: *AHiT
    options: { "": { "name": "NiyrmeAHiT{NUMBER}" } }
  - option_name: "game"
    option_result: *HK
    options: { "": { "name": "NiyrmeHK{NUMBER}" } }
  - option_name: "game"
    option_result: *OuterWilds
    options: { "": { "name": "NiyrmeOW{NUMBER}" } }
  - option_name: "game"
    option_result: *SlayTheSpire
    options: { "": { "name": "NiyrmeSpire{NUMBER}" } }
  - option_name: "game"
    option_result: *Terraria
    options: { "": { "name": "NiyrmeTerraria{NUMBER}" } }

*AHiT :
  # game
  progression_balancing: "random-range-middle-45-60"
  accessibility: "full"
  death_link: true

  # general
  &AHiTEndGoal EndGoal:
    &AHiTGoalFinale finale: 7
    &AHiTGoalRush rush_hour: 0 # 3
    &AHiTGoalSeal seal_the_deal: 0
  ShuffleStorybookPages: true
  ShuffleAlpineZiplines: true
  ShuffleSubconPaintings: true
  ShuffleActContracts: true
  MinPonCost: 20
  MaxPonCost: 80
  BadgeSellerMinItems: 5
  BadgeSellerMaxItems: 8
  LogicDifficulty:
    normal: 0
    moderate: 1
  NoPaintingSkips: true
  CTRLogic:
    time_stop_only: 0
    scooter: 1

  # acts
  ActRandomizer: "insanity"
  StartingChapter:
    1: 1 # Mafia
    2: 1 # Birds
    3: 1 # Subcon
    4: 0 # Alpine
  LowestChapterCost: 5
  HighestChapterCost: 25
  ChapterCostIncrement: "random-range-low-4-6"
  ChapterCostMinDifference: 3
  FinalChapterMinCost: 30
  FinalChapterMaxCost: 35
  FinaleShuffle: false
  ActPlando:
    &AHiTActAlpine "Alpine Free Roam": *AHiTActAlpine

  # items
  StartWithCompassBadge: true
  CompassBadgeMode: "closest"
  RandomizeHatOrder: "time_stop_last"
  YarnAvailable: 45
  YarnCostMin: 5
  YarnCostMax: 8
  MinExtraYarn: "random-range-5-15"
  HatItems: true
  UmbrellaLogic: true
  MaxExtraTimePieces: "random-range-10-15"
  YarnBalancePercent: 25
  TimePieceBalancePercent: "random-range-low-40-60"

  # Seal the Deal DLC
  EnableDLC1: false
  Tasksanity: false
  TasksanityTaskStep: 1
  TasksanityCheckCount: 18
  ShipShapeCustomTaskGoal: 0
  ExcludeTour: false

  # Nyakuza Metro DLC
  &AHiTDLCNyakuza EnableDLC2: true
  MetroMinPonCost: 10
  MetroMaxPonCost: 50
  NyakuzaThugMinShopItems: 1
  NyakuzaThugMaxShopItems: 4
  BaseballBat: true
  NoTicketSkips: "rush_hour"

  # Death Wish
  EnableDeathWish: false
  DWTimePieceRequirement: 15
  DWShuffle: false
  DWShuffleCountMin: 18
  DWShuffleCountMax: 25
  DWEnableBonus: false
  DWAutoCompleteBonuses: true
  DWExcludeAnnoyingContracts: true
  DWExcludeAnnoyingBonuses: true
  DWExcludeCandles: true
  DeathWishOnly: false

  # traps
  TrapChance: 0
  BabyTrapWeight: 0
  LaserTrapWeight: 0
  ParadeTrapWeight: 0

  # item & location options
  non_local_items:
    - "25 Pons"
    - "50 Pons"
    - "100 Pons"
    - "Hookshot Badge"
    - "Umbrella"
  start_inventory:
    "Sprint Hat": 1
  exclude_locations:
    - "Queen Vanessa's Manor - Bedroom Chest"
    - "Queen Vanessa's Manor - Hall Chest"
  priority_locations:
    - "Act Completion (Award Ceremony)"
    - "Badge Seller - Item 1"
    - "Badge Seller - Item 2"
    - "Bluefin Tunnel Thug - Item 1"
    - "Green Clean Station Thug A - Item 1"
    - "Green Clean Station Thug B - Item 1"
    - "Main Station Thug A - Item 1"
    - "Main Station Thug B - Item 1"
    - "Main Station Thug C - Item 1"
    - "Pink Paw Station Thug - Item 1"
    - "Yellow Overpass Thug A - Item 1"
    - "Yellow Overpass Thug B - Item 1"
    - "Yellow Overpass Thug C - Item 1"

  triggers:
    - option_category: *AHiT
      option_name: *AHiTEndGoal
      option_result: *AHiTGoalFinale
      options:
        *AHiT :
          MinPonCost: 30
          MaxPonCost: 100
          FinalChapterMinCost: 25
          FinalChapterMaxCost: 30
          *AHiTDLCNyakuza : false
    - option_category: *AHiT
      option_name: *AHiTEndGoal
      option_result: *AHiTGoalRush
      options:
        *AHiT :
          ActPlando:
            *AHiTActAlpine : *AHiTActAlpine
            &AHiTActNyakuza "Nyakuza Free Roam": *AHiTActNyakuza

*HK :
  # game
  progression_balancing: "random-range-low-50-55"
  accessibility: "full"

  # randomization
  RandomizeDreamers: true
  RandomizeSkills: true
  RandomizeFocus: false
  RandomizeSwim: true
  RandomizeCharms: true
  RandomizeKeys: true
  RandomizeMaskShards: true
  RandomizeVesselFragments: true
  RandomizeCharmNotches: true
  RandomizePaleOre: true
  RandomizeGeoChests: false
  RandomizeJunkPitChests: true
  RandomizeRancidEggs: true
  RandomizeRelics: true
  RandomizeWhisperingRoots: false
  RandomizeBossEssence: false
  RandomizeGrubs: true
  RandomizeMimics: false
  RandomizeMaps: true
  RandomizeStags: false
  RandomizeLifebloodCocoons: true
  RandomizeGrimmkinFlames: true
  RandomizeJournalEntries: false
  RandomizeNail: false
  RandomizeGeoRocks: false
  RandomizeBossGeo: true
  RandomizeSoulTotems: false
  RandomizeLoreTablets: false
  RandomizeElevatorPass: true

  # skips
  PreciseMovement: false
  ProficientCombat: false
  BackgroundObjectPogos: false
  EnemyPogos: false
  ObscureSkips: false
  ShadeSkips: false
  InfectionSkips: false
  FireballSkips: false
  SpikeTunnels: false
  AcidSkips: false
  DamageBoosts: false
  DangerousSkips: false
  DarkRooms: false
  ComplexSkips: false
  DifficultSkips: false

  RemoveSpellUpgrades: false
  StartLocation:
    "king's_pass": 1
  Goal:
    any: 1
    hollowknight: 0
    siblings: 0
    radiance: 0
    godhome: 0
    godhome_flower: 0
    grub_hunt: 0
  GrubHuntGoal: "random-high"
  WhitePalace:
    exclude: 0
    kingfragment: 0
    nopathofpain: 1
    include: 0
  ExtraPlatforms: true
  AddUnshuffledLocations: false
  StartingGeo: "random-range-low-0-100"

  # deathlink
  DeathLink: false
  DeathLinkShade:
    vanilla: 0
    shadeless: 0
    shade: 1
  DeathLinkBreaksFragileCharms: false

  # shops
  MinimumGeoPrice: 1
  MaximumGeoPrice: "random-range-middle-400-600"
  MinimumGrubPrice: 1
  MaximumGrubPrice: "random-range-middle-20-30"
  MinimumEssencePrice: 1
  MaximumEssencePrice: "random-range-middle-1200-1800"
  MinimumCharmPrice: 1
  MaximumCharmPrice: "random-range-low-20-30"
  RandomCharmCosts: "random-range-middle-75-105"
  MinimumEggPrice: 1
  MaximumEggPrice: "random-range-middle-8-12"
  EggShopSlots: "random-range-low-2-6"
  SlyShopSlots: "random-range-middle-6-12"
  SlyKeyShopSlots: "random-range-middle-4-8"
  IseldaShopSlots: "random-range-middle-3-6"
  SalubraShopSlots: "random-range-low-4-7"
  SalubraCharmShopSlots: "random-range-low-4-7"
  LegEaterShopSlots: "random-range-low-3-5"
  GrubfatherRewardSlots: "random-range-middle-5-10"
  SeerRewardSlots: "random-range-low-7-10"
  ExtraShopSlots: "random-range-low-0-4"

  # cursed abilities
  SplitCrystalHeart: false
  SplitMothwingCloak: false
  SplitMantisClaw: false

  # costsanity
  CostSanity:
    "off": 1
    "on": 0
    "shopsonly": 0
    "notshops": 0
  CostSanityHybridChance: "random-range-middle-5-10"
  CostSanityEggWeight: 0
  CostSanityGrubWeight: 0
  CostSanityEssenceWeight: 0
  CostSanityCharmWeight: 0
  CostSanityGeoWeight: 0

*OuterWilds :
  # game
  progression_balancing: "random-range-middle-50-60"
  accessibility: "full"
  goal:
    "song_of_five": 1
    "song_of_the_nomai": 1
    "song_of_the_stranger": 0
    "song_of_six": 1
    "song_of_seven": 0
    "echoes_of_the_eye": 0
  spawn:
    "vanilla": 1
    "hourglass_twins": 0
    "timber_hearth": 0
    "brittle_hollow": 0
    "giants_deep": 0
    "stranger": 0
    "random_non_vanilla": 0
  early_key_item:
    "off": 1
    "any": 0
    "translator": 0
    "nomai_warp_codes": 0
    "launch_codes": 0
    "stranger_light_modulator": 0

  # DLC
  enable_eote_dlc: false
  dlc_only: false

  # randomization
  randomize_coordinates: true
  randomize_orbits: false
  randomize_rotations: false
  randomize_warp_platforms: false
  randomize_dark_bramble_layout: false

  # traps
  trap_chance: 5
  trap_type_weights:
    "Audio Trap": 1
    "HUD Corruption Trap": 1
    "Ice Physics Trap": 0
    "Map Disable Trap": 0
    "Nap Trap": 0
    "Ship Damage Trap": 0
    "Suit Puncture Trap": 1
    "Supernova Trap": 0

  # misc
  upgrade_counts:
    "Boost Duration Upgrade": 3
    "Fuel Capacity Upgrade": 3
    "Oxygen Capacity Upgrade": 3
  death_link:
    "off": 1
    "default": 0  # player caused/non-natural
    "all_deaths": 0
  logsanity: false
  shuffle_spacesuit: false
  split_translator: false

  # mods
  enable_hn1_mod: false  # Hearth's Neighbor
  enable_outsider_mod: false  # The Outsider
  enable_ac_mod: false  # Astral Codec
  enable_hn2_mod: false  # Hearth's Neighbor 2
  enable_fq_mod: false  # Fret's Quest

*SlayTheSpire :
  # game
  progression_balancing: "random-range-middle-45-55"
  accessibility: "full"
  character:
    # vanilla
    "the_ironclad": 0
    "the_silent": 1
    "the_defect": 1
    "the_watcher": 0
    # modded
    "the_hermit": 0
    "the_slime_boss": 0
    "the_guardian": 0
    "the_hexaghost": 0
    "the_champ": 0
    "the_gremlins": 0
    "the_automaton": 0
    "the_snecko": 0
    "spire_take_the_wheel": 0
  ascension: 0
  final_act: true
  downfall: false
  death_link:
    0: 1
    "random-range-high-10-30": 0

*Terraria :
  # game
  progression_balancing: "random-range-low-50-55"
  accessibility: "full"
  goal:
    "mechanical_bosses": 1
    "plantera": 0
    "golem": 0
    "empress_of_light": 0
    "lunatic_cultist": 0
    "moon_lord": 0
    "zenith": 0
  achievements:
    "none": 0
    "exclude_grindy": 1
    "exclude_fishing": 0
    "all": 0
  fill_extra_checks_with: "useful_items"
  death_link: false
  non_local_items:
    - "Hardmode"
  priority_locations:
    - "Wall of Flesh"
