name: niyrme-side{number}

requires:
  version: 0.6.2

x-option-presets:
  - &OptionPresetSync "sync"
  - &OptionPresetAsync "async"

&OptionPreset "x-option.preset": *OptionPresetSync

game:
  &STPPC "Simon Tatham's Portable Puzzle Collection": 2
  &YachtDice "Yacht Dice": 1

*STPPC :
  # game
  progression_balancing: "random-range-middle-30-50"
  accessibility: "full"

  # puzzle optios
  puzzle_count: "random-range-low-15-20"
  starting_puzzles: 2
  completion_percentage: "random-range-middle-75-85"

  min_difficulty:
    "easy": 1
    "normal": 0
    "hard": 0

  max_difficulty:
    "easy": 0
    "normal": 1
    "hard": 0
    "ridiculous": 0

  genre_weights:
    "blackbox": 0
    "bridges": 1
    "cube": 0
    "dominosa": 0
    "fifteen": 0
    "filling": 0
    "flip": 0
    "flood": 1
    "galaxies": 0
    "guess": 0
    "inertia": 0
    "keen": 0
    "lightup": 0
    "loopy": 0
    "magnets": 0
    "map": 1
    "mines": 2
    "mosaic": 0
    "net": 0
    "netslide": 0
    "palisade": 0
    "pattern": 3
    "pearl": 0
    "pegs": 0
    "range": 0
    "rect": 0
    "samegame": 0
    "signpost": 3
    "singles": 0
    "sixteen": 0
    "slant": 0
    "solo": 2
    "tents": 0
    "towers": 0
    "tracks": 0
    "twiddle": 0
    "undead": 0
    "unequal": 0
    "unruly": 0
    "untangle": 1

*YachtDice :
  # game
  progression_balancing: "random-range-middle-30-50"
  accessibility: "minimal"
  game_difficulty: "hard"
  score_for_last_check: 1000
  &YachtGoalScore score_for_goal: "random-range-low-777-999"
  &YachtMinDiceAndRolls minimal_number_of_dice_and_rolls:
    "5_dice_and_3_rolls": 23
    "5_dice_and_5_rolls": 0
    &YachtMinDiceAndRolls6d4r "6_dice_and_4_rolls": 1
    &YachtMinDiceAndRolls7d3r "7_dice_and_3_rolls": 1
    "8_dice_and_2_rolls": 0
  number_of_dice_fragments_per_dice: "random-high"
  number_of_roll_fragments_per_roll: "random-high"

  percentage_alternative_categories: "random-range-low-10-30"

  # extra progression
  weight_of_dice: 5
  weight_of_roll: 20
  weight_of_fixed_score_multiplier: 30
  weight_of_step_score_multiplier: 0
  weight_of_double_category: 50
  weight_of_points: 20
  points_size: "mix"

  # extra items
  minimize_extra_items: "no_dont"
  add_bonus_points: "sure"
  add_story_chapters: "never"
  which_story: "random_story"

  # misc
  allow_manual_input: "no_dont_allow"

  triggers:
    - option_category: *YachtDice
      option_name: *YachtMinDiceAndRolls
      option_result: *YachtMinDiceAndRolls6d4r
      options:
        *YachtDice :
          *YachtGoalScore : "random-range-high-777-999"
    - option_category: *YachtDice
      option_name: *YachtMinDiceAndRolls
      option_result: *YachtMinDiceAndRolls7d3r
      options:
        *YachtDice :
          *YachtGoalScore : "random-range-middle-777-999"

triggers:
  # names
  - option_name: game
    option_result: *STPPC
    options: { "": { "name": "niyrme-STPPC{number}" } }
  - option_name: game
    option_result: *YachtDice
    options: { "": { "name": "niyrme-yacht{number}" } }
