game: &AHiT "A Hat in Time"

name: "niyrme-AHiT{NUMBER}"

requires:
  version: 0.6.2

x-option-presets:
  - &OptionPresetSync "sync"
  - &OptionPresetAsync "async"

&OptionPreset "x-option.preset": *OptionPresetSync

*AHiT :
  # game
  progression_balancing: "random-range-middle-40-50"
  accessibility:
    "full": 1
    "minimal": 0
  death_link: true

  # general
  &AHiTEndGoal EndGoal:
    &AHiTGoalFinale finale: 7
    &AHiTGoalRush rush_hour: 0 # 3
    &AHiTGoalSeal seal_the_deal: 0
  ShuffleStorybookPages: true
  ShuffleAlpineZiplines: true
  ShuffleSubconPaintings: true
  ShuffleActContracts: true
  MinPonCost: 20
  MaxPonCost: 80
  BadgeSellerMinItems: 5
  BadgeSellerMaxItems: 8
  LogicDifficulty: "moderate"
  NoPaintingSkips: true
  CTRLogic:
    time_stop_only: 0
    scooter: 1
    sprint: 0
    nothing: 0

  # acts
  ActRandomizer: "insanity"
  StartingChapter: "random"
  LowestChapterCost: "random-range-low-4-7"
  HighestChapterCost: "random-range-middle-25-30"
  ChapterCostIncrement:
    5: 1
    6: 1
  ChapterCostMinDifference:
    4: 1
    5: 1
  &GoalMinCost FinalChapterMinCost: 30
  &GoalMaxCost FinalChapterMaxCost: 35
  FinaleShuffle: true

  # items
  StartWithCompassBadge: true
  CompassBadgeMode: "closest"
  RandomizeHatOrder: "time_stop_last"
  YarnAvailable: "random-range-middle-40-50"
  YarnCostMin: 5
  YarnCostMax: 8
  MinExtraYarn: "random-range-middle-5-15"
  HatItems: true
  UmbrellaLogic: true
  MaxExtraTimePieces: "random-range-middle-8-12"
  YarnBalancePercent: 25
  TimePieceBalancePercent: "random-range-low-40-60"

  # DLC: Seal the Deal
  EnableDLC1: false
  Tasksanity: false
  TasksanityTaskStep: 1
  TasksanityCheckCount: 18
  ShipShapeCustomTaskGoal: 0
  ExcludeTour: false

  # DLC: Nyakuza Metro
  &AHiTDLCNyakuza EnableDLC2: true
  MetroMinPonCost: 10
  MetroMaxPonCost: 50
  NyakuzaThugMinShopItems: 1
  NyakuzaThugMaxShopItems: 4
  BaseballBat: true
  NoTicketSkips: "rush_hour"

  # Death Wish
  EnableDeathWish: false
  DWTimePieceRequirement: 15
  DWShuffle: false
  DWShuffleCountMin: 18
  DWShuffleCountMax: 25
  DWEnableBonus: false
  DWAutoCompleteBonuses: true
  DWExcludeAnnoyingContracts: true
  DWExcludeAnnoyingBonuses: true
  DWExcludeCandles: true
  DeathWishOnly: false

  # traps
  TrapChance: 0
  BabyTrapWeight: 0
  LaserTrapWeight: 0
  ParadeTrapWeight: 0

  # plando, item & location options
  non_local_items:
    - "Hookshot Badge"
    - "Umbrella"
    - "Dweller Mask"
  start_inventory_from_pool:
    "Sprint Hat": 1
  exclude_locations:
    - "Queen Vanessa's Manor - Bedroom Chest"
    - "Queen Vanessa's Manor - Hall Chest"
    - &LocationActCompletionTheBigParade "Act Completion (The Big Parade)"
  priority_locations:
    - "Act Completion (Award Ceremony)"
    - "Badge Seller - Item 1"
    - "Badge Seller - Item 2"
    - "Mafia Boss Shop Item"
    # Nyakuza DLC
    - "Bluefin Tunnel Thug - Item 1"
    - "Green Clean Station Thug A - Item 1"
    - "Green Clean Station Thug B - Item 1"
    - "Main Station Thug A - Item 1"
    - "Main Station Thug B - Item 1"
    - "Main Station Thug C - Item 1"
    - "Pink Paw Station Thug - Item 1"
    - "Yellow Overpass Thug A - Item 1"
    - "Yellow Overpass Thug B - Item 1"
    - "Yellow Overpass Thug C - Item 1"

  ActPlando:
    "Dead Bird Studio Basement": "The Big Parade"

triggers:
  # sync
  - option_name: *OptionPreset
    option_result: *OptionPresetSync
    options:
      *AHiT :
        +triggers:
          - option_category: *AHiT
            option_name: *AHiTEndGoal
            option_result: *AHiTGoalFinale
            options:
              *AHiT :
                MinPonCost: 30
                MaxPonCost: 100
                *GoalMinCost : 25
                *GoalMaxCost : 35
                *AHiTDLCNyakuza : false
  # async
  - option_name: *OptionPreset
    option_result: *OptionPresetAsync
    options:
      *AHiT :
        progression_balancing: "random-range-low-10-30"
        accessibility:
          "full": 2
          "minimal": 1
        death_link: false
        *AHiTEndGoal :
          *AHiTGoalFinale : 7
          *AHiTGoalRush : 3
          *AHiTGoalSeal : 0
        +non_local_items:
          - "Brewing Hat"
          - "Ice Hat"
        -exclude_locations:
          - *LocationActCompletionTheBigParade
        priority_locations: []
        ActPlando: {}
        *GoalMinCost : 35
        *GoalMaxCost : 40
