game: &STPPC "Simon Tatham's Portable Puzzle Collection"

name: "niyrme-STPPC{number}"

requires:
  version: 0.6.2

*STPPC :
  # game
  progression_balancing: "random-range-low-15-25"
  accessibility: "full"

  # puzzle optios
  puzzle_count: "random-range-middle-20-30"
  starting_puzzles: 2
  completion_percentage: 80

  min_difficulty:
    "easy": 1
    "normal": 0
    "hard": 0

  max_difficulty:
    "easy": 0
    "normal": 1
    "hard": 0
    "ridiculous": 0

  genre_weights:
    "blackbox": 0
    "bridges": 0
    "cube": 0
    "dominosa": 0
    "fifteen": 0
    "filling": 0
    "flip": 0
    "flood": 0
    "galaxies": 0
    "guess": 0
    "inertia": 0
    "keen": 0
    "lightup": 0
    "loopy": 0
    "magnets": 0
    "map": 0
    &Genre_Mines "mines": 1
    "mosaic": 0
    "net": 0
    "netslide": 0
    "palisade": 0
    &Genre_Pattern "pattern": 10
    "pearl": 0
    "pegs": 0
    "range": 0
    "rect": 0
    "samegame": 0
    &Genre_Signpost "signpost": 2
    "singles": 0
    "sixteen": 0
    "slant": 0
    "solo": 0
    "tents": 0
    "towers": 0
    "tracks": 0
    "twiddle": 0
    "undead": 0
    "unequal": 0
    "unruly": 0
    &Genre_Untangle "untangle": 1

  preset_overrides:
    *Genre_Mines :
      - "9x9n10"
      - "13x13n30"
      - "16x16n40"
    *Genre_Pattern :
      - "10x10"
      - "15x15"
    *Genre_Signpost :
      - "4x4"
      - "4x4c"
    *Genre_Untangle :
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
