game: &STGPuzzleCollection "Simon Tatham's Portable Puzzle Collection"

name: "niyrme-STPPC{number}"

requires:
  version: 0.6.2

*STGPuzzleCollection :
  # game
  progression_balancing: 50
  accessibility: "full"

  # puzzle optios
  puzzle_count: "random-range-low-10-15"
  starting_puzzles: 2
  completion_percentage: 80

  min_difficulty:
    "easy": 1
    "normal": 0
    "hard": 0

  max_difficulty:
    "easy": 0
    "normal": 1
    "hard": 0
    "ridiculous": 0

  genre_weights:
    "blackbox": 0
    "bridges": 1
    "cube": 0
    "dominosa": 0
    "fifteen": 0
    "filling": 0
    "flip": 0
    "flood": 1
    "galaxies": 0
    "guess": 0
    "inertia": 0
    "keen": 0
    "lightup": 0
    "loopy": 0
    "magnets": 0
    "map": 1
    "mines": 1
    "mosaic": 0
    "net": 1
    "netslide": 1
    "palisade": 0
    "pattern": 2
    "pearl": 0
    "pegs": 0
    "range": 0
    "rect": 0
    "samegame": 0
    "signpost": 2
    "singles": 0
    "sixteen": 0
    "slant": 0
    "solo": 1
    "tents": 0
    "towers": 0
    "tracks": 0
    "twiddle": 0
    "undead": 0
    "unequal": 0
    "unruly": 0
    "untangle": 1
