game: &YachtDice "Yacht Dice"

name: "niyrme-yacht{number}"

*YachtDice :
  # game
  progression_balancing: "random-range-middle-30-50"
  accessibility: "full"
  game_difficulty: "hard"
  score_for_last_check: 1000
  &YachtGoalScore score_for_goal: "random-range-low-777-999"
  &YachtMinDiceAndRolls minimal_number_of_dice_and_rolls:
    "5_dice_and_3_rolls": 23
    "5_dice_and_5_rolls": 0
    &YachtMinDiceAndRolls6d4r "6_dice_and_4_rolls": 1
    &YachtMinDiceAndRolls7d3r "7_dice_and_3_rolls": 1
    "8_dice_and_2_rolls": 0
  number_of_dice_fragments_per_dice: "random-high"
  number_of_roll_fragments_per_roll: "random-high"
  number_of_starting_categories:
    2: 9
    3: 1

  alternative_categories: "random-range-low-1-4"

  # extra progression
  weight_of_dice: 5
  weight_of_roll: 20
  weight_of_fixed_score_multiplier: 30
  weight_of_step_score_multiplier: 0
  weight_of_double_category: 50
  weight_of_points: 20
  points_size: "mix"

  # extra items
  minimize_extra_items: "no_dont"
  add_bonus_points: "sure"
  add_story_chapters: "never"
  which_story: "random_story"

  # misc
  allow_manual_input: "no_dont_allow"
  receive_death_link: "yes"

  triggers:
    - option_category: *YachtDice
      option_name: *YachtMinDiceAndRolls
      option_result: *YachtMinDiceAndRolls6d4r
      options:
        *YachtDice :
          *YachtGoalScore : "random-range-high-777-999"
    - option_category: *YachtDice
      option_name: *YachtMinDiceAndRolls
      option_result: *YachtMinDiceAndRolls7d3r
      options:
        *YachtDice :
          *YachtGoalScore : "random-range-middle-777-999"
